---
title: "A genome-wide assessment of genetic diversity and population structure of Korean native cattle breeds"
author: "Juan Carlos Segura Cabanillas"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 4
    number-sections: true
    self-contained: true
    output-file: "index"
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  echo: false
---

# Referencias

- [https://doi.org/10.1186/s12863-016-0444-8](https://doi.org/10.1186/s12863-016-0444-8)

# Librerias y configuración

```{r}
#| label: setup

source('https://inkaverse.com/setup.r')
```

# Importación de datos

> Base de datos de diversidad genómica y clasificación racial de Sharma et al. (2016):

```{r}
# Metadatos taxonómicos y raciales
taxa <- tibble(
  Breed = c("Brown_Hanwoo", "Brindle_Hanwoo", "Jeju_Black", "Yanbian", "Wagyu", 
            "Mongolian", "Angus", "Hereford", "Holstein", "Jersey", 
            "Limousin", "Brown_Swiss", "NDama", "Sheko", "Nelore", 
            "Gir", "Brahman", "Hainan", "Luxi", "Qinchuan"),
  Code = c("BH", "BNH", "JB", "YB", "WAGY", 
           "MG", "ANG", "HFD", "HOL", "JER", 
           "LMS", "BS", "ND", "SHK", "NEL", 
           "GIR", "BRM", "HN", "LX", "QC"),
  Origin = c("Corea", "Corea", "Corea_Jeju", "China", "Japon", 
             "Mongolia", "Reino_Unido", "Reino_Unido", "Paises_Bajos", "Reino_Unido", 
             "Francia", "Suiza", "Guinea", "Etiopia", "Brasil", 
             "India", "EEUU", "China", "China", "China"),
  Subspecies = c("Taurino_Asiatico", "Taurino_Asiatico", "Taurino_Asiatico", "Taurino_Asiatico", "Taurino_Asiatico", 
                 "Taurino_Asiatico", "Taurino_Europeo", "Taurino_Europeo", "Taurino_Europeo", "Taurino_Europeo", 
                 "Taurino_Europeo", "Taurino_Europeo", "Taurino_Africano", "Taurino_Africano", "Cebuino_Indicus", 
                 "Cebuino_Indicus", "Cebuino_Indicus", "Cebuino_Indicus", "Taurino_Asiatico", "Taurino_Asiatico"),
  Purpose = c("Carne", "Carne", "Carne", "Carne_Tiro", "Carne", 
              "Carne", "Carne", "Carne", "Leche", "Leche", 
              "Doble_Proposito", "Doble_Proposito", "Adaptado", "Adaptado", "Carne", 
              "Leche", "Carne", "Rustico", "Carne", "Carne")
)

# Parámetros cuantitativos genómicos
geno <- tibble(
  Code = c("BH", "BNH", "JB", "YB", "WAGY", 
           "MG", "ANG", "HFD", "HOL", "JER", 
           "LMS", "BS", "ND", "SHK", "NEL", 
           "GIR", "BRM", "HN", "LX", "QC"),
  Sample_Size = c(120, 20, 20, 39, 12, 9, 25, 20, 80, 29, 25, 22, 40, 36, 30, 20, 20, 9, 15, 10),
  Ho = c(0.3352, 0.3310, 0.3268, 0.3437, 0.3039, 0.3210, 0.3750, 0.3806, 0.3711, 0.3650, 0.3690, 0.3720, 0.2721, 0.2850, 0.2019, 0.2105, 0.2225, 0.2410, 0.3390, 0.3320),
  He = c(0.2625, 0.2551, 0.2546, 0.2710, 0.2340, 0.2510, 0.2890, 0.2930, 0.2875, 0.2810, 0.2850, 0.2880, 0.2106, 0.2230, 0.1542, 0.1610, 0.1764, 0.1890, 0.2680, 0.2610),
  Fis = c(-0.2100, -0.2298, -0.2156, -0.2048, -0.2203, -0.2110, -0.2250, -0.2297, -0.2286, -0.2240, -0.2260, -0.2250, -0.2114, -0.2150, -0.1990, -0.1920, -0.1607, -0.1750, -0.2080, -0.2100),
  Polymorphic_Pct = c(91.2, 88.5, 87.4, 92.1, 82.3, 85.0, 94.2, 95.1, 94.8, 93.5, 94.0, 94.3, 76.5, 78.2, 62.4, 64.1, 68.3, 70.2, 90.8, 89.5),
  MAF_Mean = c(0.215, 0.208, 0.205, 0.220, 0.192, 0.201, 0.235, 0.241, 0.238, 0.230, 0.232, 0.236, 0.175, 0.181, 0.125, 0.130, 0.142, 0.150, 0.218, 0.212),
  Allelic_Richness = c(1.91, 1.88, 1.87, 1.92, 1.82, 1.85, 1.94, 1.95, 1.95, 1.93, 1.94, 1.94, 1.76, 1.78, 1.62, 1.64, 1.68, 1.70, 1.90, 1.89)
)

str(geno)
str(taxa)
```

# Unir base de datos

```{r}
fb <- merge(geno, taxa, by = "Code") %>% 
  dplyr::select(Breed, Code, Origin, Subspecies, Purpose, everything()) %>% 
  mutate(across(Sample_Size:ncol(.), ~ as.numeric(.)))

str(fb)

fb %>% kable()
```

# Análisis de componentes principales - PCA

```{r}
mv <- PCA(X = fb, scale.unit = TRUE, quali.sup = 1:5, graph = FALSE)

var <- plot.PCA(mv, choix = c("var"), cex = 0.7)

ind <- plot.PCA(mv, choix = c("ind"), cex = 0.7
                , label = "ind"
                , invisible = "quali"
                , habillage = 4
                )

list(var, ind) %>% 
  plot_grid(plotlist = ., ncol = 2, labels = "auto")

summary(mv, nbelements = Inf, nb.dec = 2)

pcainfo <- factoextra::get_pca_var(mv)
pcainfo$cor
pcainfo$contrib
```

# Analisis de Cluster

```{r}
cls <- HCPC(mv, graph = FALSE)

plot.HCPC(cls, choice = "map", nb.clust = -1, draw.tree = FALSE)
plot.HCPC(cls, choice = "tree", nb.clust = -1, draw.tree = FALSE)

map <- \(){
  plot.HCPC(cls, choice = "map", nb.clust = -1, draw.tree = FALSE)
}

list(var, map) %>% 
  plot_grid(plotlist = ., ncol = 2, labels = "auto")
```